FROM postgres:13

# Add custom startup script
COPY ./data/postgres/configs/setup-postgres.sh /docker-entrypoint-initdb.d/setup-postgres.sh

# Make sure the script is executable
RUN chmod +x /docker-entrypoint-initdb.d/setup-postgres.sh
