
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.2.23
    container_name: clickhouse
    # restart: always
    env_file:
      - .env
    ports:
      - 8123:8123
      - 9000:9000
    networks:
      - franco
    volumes:
      - ./data/clickhouse/db_data:/var/lib/clickhouse/ #- main folder where ClickHouse stores the data
      - ./data/clickhouse/logs:/var/log/clickhouse-server/ #- logs
      - ./data/clickhouse/init:/docker-entrypoint-initdb.d/ # entrypoint
      # - ./data/clickhouse/configs/config.xml:/etc/clickhouse-server/config.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5433:5432
    networks:
      - franco
    # command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./data/postgres/db_data/:/var/lib/postgresql/data
      # - ./data/postgres/configs/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "franco"]
      interval: 5s
      retries: 5
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: padmin
    env_file:
    - .env
    ports:
      - "89:80"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - franco

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    networks:
      - franco

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zookeeper
    networks:
      - franco

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - 9001:9000
    networks:
      - franco
    environment:
      KAFKA_BROKERCONNECT: kafka:19092
      # JVM_OPTS: "-Xms16M -Xmx512M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka

  debezium:
    image: debezium/connect
    container_name: debezium
    restart: "no"
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:19092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
    depends_on:
      - kafka
    networks:
      - franco
    volumes:
      - ./data/debezium/home:/home
      - ./data/debezium/connect/debezium-connector-clickhouse:/kafka/connect/debezium-connector-clickhouse
  
  superset:
    container_name: superset
    build:
      context: .
      dockerfile: ./superset/Dockerfile.superset
    env_file:
      - .env
    ports:
      - "8089:8088"
    networks:
      - franco
    volumes:
      - ./data/superset/home:/home/superset
      - ./data/superset/data:/var/lib/superset
    logging:
      options:
        max-size: 10m
        max-file: "3"

networks:
  franco:
    external: true

