tables:
  customer:
    columns:
      customer_id: "SERIAL NOT NULL"
      last_name: "varchar(50) NULL"
      address_line1: "varchar(50) NULL"
      address_line2: "varchar(50) NULL"
      birth_date: "varchar(50) NULL"
      age: "varchar(50) NULL"
      commute_distance: "varchar(50) NULL"
      customer_alternate_key: "varchar(50) NULL"
      customer_key: "varchar(50) NULL"
      date_first_purchase: "varchar(50) NULL"
      email_address: "varchar(50) NULL"
      english_education: "varchar(50) NULL"
      english_occupation: "varchar(50) NULL"
      french_education: "varchar(50) NULL"
      first_name: "varchar(50) NULL"
      french_occupation: "varchar(50) NULL"
      gender: "varchar(50) NULL"
      house_owner_flag: "varchar(50) NULL"
      marital_status: "varchar(50) NULL"
      middle_name: "varchar(50) NULL"
      name_style: "varchar(50) NULL"
      number_cars_owned: "varchar(50) NULL"
      number_children_at_home: "varchar(50) NULL"
      phone: "varchar(50) NULL"
      spanish_education: "varchar(50) NULL"
      spanish_occupation: "varchar(50) NULL"
      suffix: "varchar(50) NULL"
      title: "varchar(50) NULL"
      total_children: "varchar(50) NULL"
      yearly_income: "varchar(50) NULL"
    primary_key: "customer_id"

  sales_territory:
    columns:
      sales_territory_id: "SERIAL NOT NULL"
      sales_territory_country: "varchar(50) NULL"
      sales_territory_region: "varchar(50) NULL"
      sales_territory_city: "varchar(50) NULL"
    primary_key: "sales_territory_id"

  employee:
    columns:
      employee_id: "SERIAL NOT NULL"
      employee_name: "varchar(50) NULL"
      employee_territory_region: "varchar(50) NULL"
    primary_key: "employee_id"

  sales:
    columns:
      sales_id: "SERIAL NOT NULL"
      currencykey: "varchar(50) NULL"
      customerkey: "varchar(50) NULL"
      discount_amount: "varchar(50) NULL"
      duedate: "varchar(50) NULL"
      duedatekey: "varchar(50) NULL"
      extended_amount: "varchar(50) NULL"
      freight: "varchar(50) NULL"
      order_date: "varchar(50) NULL"
      order_quantity: "varchar(50) NULL"
      product_standard_cost: "varchar(50) NULL"
      revision_number: "varchar(50) NULL"
      sales_amount: "varchar(50) NULL"
      sales_order_line_number: "varchar(50) NULL"
      sales_order_number: "varchar(50) NULL"
      salesterritorykey: "varchar(50) NULL"
      shipdate: "varchar(50) NULL"
      tax_amt: "varchar(50) NULL"
      total_product_cost: "varchar(50) NULL"
      unit_price: "varchar(50) NULL"
      unit_price_discount_pct: "varchar(50) NULL"
      employee_id: "INT NOT NULL REFERENCES employee (employee_id)"
    primary_key: "sales_id"
